@startuml
hotelController -> hotelService : createHotel(HotelVO hotelVO)
activate hotelController
activate hotelService
hotelService -> HotelVO : createHotel()
activate HotelVO
HotelVO -> hotelService
deactivate HotelVO
hotelService -> hotelMapper :  createHotel(HotelVO hotelVO)
activate hotelMapper
hotelMapper -> DataBase : createHotel(HotelVO hotelVO)
activate DataBase
DataBase -> hotelMapper
deactivate DataBase
hotelMapper -> hotelService
deactivate hotelMapper
hotelService -> hotelController:
deactivate hotelService
deactivate hotelController

@enduml