@startuml
accountController -> accountService : login(UserForm userForm)
activate accountController
activate accountService
accountService -> UserForm : createUserForm()
activate UserForm
UserForm -> accountService
deactivate UserForm
accountService -> accountMapper :  getAccountByName(String userForm.email)
activate accountMapper
accountMapper -> DataBase : getAccountByName(String userForm.email)
activate DataBase
DataBase -> accountMapper
deactivate DataBase
accountMapper -> accountService
deactivate accountMapper
accountService -> accountController:
deactivate accountService
deactivate accountController
@enduml