spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Hotel?serverTimezone=CTT&characterEncoding=UTF-8&useLocalSessionState=true
    username: Allen
    password: qweasd
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  redis:
    host: localhost
#    password: seecoder
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 10
        max-wait: 10000
      shutdown-timeout: 20000
    database: 0
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8

token-time:
  short: 30
  long: 60

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
