spring:
  datasource:
    url: jdbc:h2:mem:Hotel;MODE=MySQL
    username: Allen
    password: qweasd
    driver-class-name: org.h2.Driver
    initialization-mode: ALWAYS
    schema: classpath:hotel.sql
  h2:
    console:
      enabled: true
  thymeleaf:
     cache: false
  jackson:
    time-zone: GMT+8
  redis:
    host: 106.15.248.13
    password: seecoder
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5
        max-wait: 1ms
      shutdown-timeout: 100ms
    database: 1

token-time:
  short: 300
  long: 300

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
